services:
  postgres:
    image: postgres:15-alpine
    container_name: trab-final-mc-postgres
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trab-mc-network
  microservice:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trab-final-mc-service
    depends_on:
      - postgres
    ports:
      - "3001:3000"   # Porta do microservi√ßo
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    networks:
      - trab-mc-network

volumes:
  postgres_data:

networks:
  trab-mc-network:
    driver: bridge
